questions = [
    {
        "question": "Osaan myydä 2 pullaa kolmen hinnalla ",
        "effect": {
            "myynti": 100,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Tekemäni pehmikset ovat kuin taideteoksia",
        "effect": {
            "myynti": 100,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Osaan toimia kiireessä",
        "effect": {
            "myynti": 100,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Haluan tehdä ruokaa ja onnistun siinä leikkaamatta sormeeni",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 100,
        },
    },
    {
        "question": "Haluan annostella muille ruokaa ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 100,
        },
    },
    {
        "question": "Tiedän mikä on hyvä annoskoko",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 100,
        },
    },
    {
        "question": "Minua kiinnostaa asiakaspalvelu ",
        "effect": {
            "myynti": 0,
            "palvelu": 100,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Pystyn puhumaan ja kirjoittamaan yhtä aikaa",
        "effect": {
            "myynti": 0,
            "palvelu": 100,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Haluan olla tekemisissä muiden leiriläisen kanssa",
        "effect": {
            "myynti": 0,
            "palvelu": 100,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Tykkään näyttää muille millaista leiriarki on ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 100,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Minulla on visuaalista silmää",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 100,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Tunnen oloni luonnolliseksi sekä kameran edessä ja takana",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 100,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Haluan tehdä muille ohjelmaa ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 100,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Tykkään leikkiä lasten kanssa ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 100,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Pidän erilaisista kädentaidoista ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 100,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Tykkään huolehtia asioiden toimivuudesta ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 100,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Haluan pitää saunat läpiminä",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 100,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Haluan tehdä jotain fyysistä työtä ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 100,
            "tekniikka": 0,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Osaan yhdistää johtoja turvallisesti toisiinsa ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 100,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Osaan käyttää miksaus/valopöytää ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 100,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Haluan huolehtia, että vesi on lämmintä ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 100,
            "liikenne": 0,
            "elintarvike": 0,
        },
    },
    {
        "question": "Tiedän kumpi on oikea ja kumpi vasen puoli",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 100,
            "elintarvike": 0,
        },
    },
    {
        "question": "Minulla on kantava ääni",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 100,
            "elintarvike": 0,
        },
    },
    {
        "question": "Tiedän liikennemerkeistä jonkun verran ",
        "effect": {
            "myynti": 0,
            "palvelu": 0,
            "ohjelma": 0,
            "some": 0,
            "huolto": 0,
            "tekniikka": 0,
            "liikenne": 100,
            "elintarvike": 0,
        },
    },
];
